version: '3.8'
services:
  redis:
    image: redis:7-alpine
    container_name: nest-worker-redis-prod
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    environment:
      - REDIS_REPLICATION_MODE=master
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

  redis-insight:
    image: redis/redisinsight:latest
    container_name: nest-worker-redis-insight-prod
    ports:
      - "5540:5540"
    environment:
      - REDIS_HOSTS=production:redis:6379
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 256M

volumes:
  redis_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/lib/redis-data

networks:
  default:
    driver: bridge